services:

  apiusuarios:
    build:
      context: .               
      dockerfile: Dockerfile  
    container_name: apiusuarios_app
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - oracle
    networks:
      - mynetwork

  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle_container
    restart: always
    environment:
      ORACLE_PASSWORD: coti
      APP_USER: user_coti
      APP_USER_PASSWORD: coti
    ports:
      - "1521:1521"
      - "5500:5500"
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - mynetwork

volumes:
  oracle_data:

networks:
  mynetwork: